### ISSUE TITLE
Google DNS

### ISSUE THREAD

**Issue by phelixnmc** [namecoin/nmcontrol#61]
For non .bit queries it should not use Google DNS servers by default but use the system default dns resolving.

**Comment by JeremyRand** [comment]
I agree, but it will be potentially complicated to handle this if the system default DNS is pointing to NMControl.  I guess that will be less of an issue once we merge the Windows registry trick, since non-.bit queries won't go to localhost by default.  In any event all that code will be rewritten when we switch to Unbound, so I'd favor deferring this until that point.

**Comment by phelixbtc** [comment]
Fixed as of https://github.com/namecoin/nmcontrol/pull/70
